### PR TITLE
Reduce settings needed for every release

### PR DESCRIPTION
**Pull request by ekohl**
This explicitly requires FULLVERSION to be set when needed. This allows them to be dropped from client and pulpcore settings.

It also automatically sets it for `FOREMAN_VERSION`, not in every single settings file.

### CODE REVIEW

**Comment by ekohl** [comment]
Untested for now, so a draft.

@ehelms is `FULLVERSION` needed to be set for Candlepin, or can it be dropped like Pulpcore?

**Review by ehelms — APPROVED** [review]
Looks sane to me.

**Comment by ehelms** [comment]
@ekohl I'd love for you to revisit this so I can finish off the Copr work and align our use of scripts in CI and locally.

**Comment by ekohl** [comment]
@evgeni mind giving this a sanity check?

**Review by evgeni — APPROVED** [review]
I did not check if there are *other* scripts that expect $FULLVERSION and didn't get the `require_fullversion` treatment, but the diff here in the PR looks sane to me!

**Pull request merged**
